### ISSUE TITLE
When the plug-in can be installed on phonegap build 3.0+ ?

### ISSUE THREAD

**Issue by bau720123** [sampathpremarathna/ContactPickerUtil#3]
When the plug-in can be installed on phonegap build 3.0+ ?
Tks~

**Comment by sampathpremarathna** [comment]
I have updated the plugin, and now i'm waiting for phonegap build to update my plugin.It's been a long wait...

**Comment by mphasize** [comment]
I'm waiting for this update too, so it's cool to hear that you already put in an update. Thanks a lot! 
Let's hope that the Adobe staff approves it soon.

**Comment by bau720123** [comment]
I'm waiting for this update a long time ago，is the Adobe staff not approves it yet?

**Comment by sampathpremarathna** [comment]
Yes it is approved! Is there any problem still with the plugin? please let
me know.
Thank you for using the plugin.

On Tue, Dec 17, 2013 at 7:56 PM, bau720123 notifications@github.com wrote:

> I'm waiting for this update a long time ago，is the Adobe staff not
> approves it yet?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/sampathpremarathna/ContactPickerUtil/issues/3#issuecomment-30754487
> .

## 

_~sampathpremarathna~_

**Comment by bau720123** [comment]
but the plugin page still have the phonegap version "2.9" only
https://build.phonegap.com/plugins/114

**Comment by sampathpremarathna** [comment]
Sorry mate.That is not my plugin. :)
This is my plugin : https://build.phonegap.com/plugins/39

On Tue, Dec 17, 2013 at 8:10 PM, bau720123 notifications@github.com wrote:

> but the plugin page still have the phonegap version "2.9" only
> https://build.phonegap.com/plugins/114
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/sampathpremarathna/ContactPickerUtil/issues/3#issuecomment-30755613
> .

## 

_~sampathpremarathna~_

**Comment by bau720123** [comment]
sorry~
I used the wrong URL
but your url still have the phonegap version "2.9" only
https://build.phonegap.com/plugins/39

**Comment by sampathpremarathna** [comment]
Sorry from here also.
It seems phonegap still haven't approved the update. Plugin page still
showing the old version of git repository.I'll check whether there is an
problem with the update (but i still believe there isn't).

On Tue, Dec 17, 2013 at 8:16 PM, bau720123 notifications@github.com wrote:

> sorry~
> I used the wrong URL
> but your url still have the phonegap version "2.9" only
> https://build.phonegap.com/plugins/39
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/sampathpremarathna/ContactPickerUtil/issues/3#issuecomment-30756192
> .

## 

_~sampathpremarathna~_

**Comment by bau720123** [comment]
thanks for your reply
I have to be patient wait to see ^^

**Comment by bau720123** [comment]
is there anyway to speed up the phonegap team to approved the update?
3 months pass....

**Comment by bau720123** [comment]
is anything wrong?

**Comment by sampathpremarathna** [comment]
I don't know whats wrong...

here is my plugin support at the code.

<plugin xmlns="http://cordova.apache.org/ns/plugins/1.0"
xmlns:android="http://schemas.android.com/apk/res/android"
id="com.mobitel.nalaka.piccon" version="2.0.0" versionCode="2">
    <name>ContactPickerUtil</name>
    <description>phonegap contact picker plugin</description>
    <license>MIT</license>
    <keywords>cordova,contacts,pick</keywords>

<engines>
    <engine name="cordova" version=">=2.8.0" />
</engines>

But it haven't get updated :(

On Sun, Jan 5, 2014 at 3:35 PM, bau720123 notifications@github.com wrote:

> is anything wrong?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/sampathpremarathna/ContactPickerUtil/issues/3#issuecomment-31600502
> .

## 

_~sampathpremarathna~_

**Comment by bau720123** [comment]
@_@??cordova version 2.80??

**Comment by ChrisAntaki** [comment]
Cordova supports this functionality by default now #7
